### PR TITLE
Solved Issue 24 "single instance mode" for TimeRecorder.

### PR DESCRIPTION
**Pull request by PaulHuxe**
I added a little bit of code to force the singleton mode of this app. If you try to open twice, it will silently close the second one before it can do anything.

If interested I sould be able to help you on several other issues.

### CODE REVIEW

**Comment by objorke** [comment]
could testlog files in .vs folder could be ignored?

**Comment by objorke** [comment]
regarding the syntax error, does it need to specify VS version? update appveyor.yml
https://www.appveyor.com/docs/build-environment/#choosing-image-for-your-builds

**Comment by PaulHuxe** [comment]
Yes, all these files could be ignored. I work with VS 2019 and maybe it's why these files have been modified.
The only file modification really needed is the source/TimeRecorder/program.cs

I'm new on github and I don't know if you can accept only this file or if I must do a clean commit with only this one.

**Review by sadortun — APPROVED** [review]

**Comment by sadortun** [comment]
@PaulHuxe welcome and thanks for your contribution.

You can either "amend" your previous commit and force push your new changes,  or fix the CI error. 

I think it's fine if we upgrade the project to VC 2019.

**Comment by PaulHuxe** [comment]
Ok. Let's try to upgrade to VS 2019. Going to learn how does Appveyor works.

**Comment by sadortun** [comment]
@PaulHuxe You can go on your repo : https://github.com/PaulHuxe/UsageStats/tree/Singleton and click on

image

It will merge your other PR into your repo and we'll be able to test your fix

**Comment by PaulHuxe** [comment]
Seems to work better. Thanks for the tips.

Now, going to see what I can do on other issues.

**Comment by sadortun** [comment]
@PaulHuxe thanks for your contribution!

**Pull request merged**
