### PR TITLE
Enhancement: Added "Usability Mode"

### PR DESCRIPTION
**Pull request by mfe-**
I added a "Usability Mode" functionality.
This switches the program to a kind of CompactOverlay mode which displays limited information like mouse clicks and the duration.
Also, resetting the statistics will trigger the SaveReport method. 

usage-statistics-menue
usage-statistics-compact-overlaymode

### CODE REVIEW

**Comment by objorke** [comment]
Thanks for contributing! I added some remarks, I hope we can get it even better before we merge! 

Could the "tiny" mode be even smaller? e.g. remove the menu bar? Could the minimize and maximize window buttons be hidden? And the close button?

**Comment by mfe-** [comment]
With hiding the menu I could minimize the tiny mode.
image

**Comment by mfe-** [comment]
Found this old open PR. Can this be merged or is there some work left over to do?

**Review by sadortun — APPROVED** [review]

**Comment by sadortun** [comment]
Here you go!

**Pull request merged**
